---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	triage(triage)
	jira_agent(jira_agent)
	confluence_agent(confluence_agent)
	status_agent(status_agent)
	__end__([<p>__end__</p>]):::last
	__start__ --> triage;
	triage -.-> __end__;
	triage -. &nbsp;confluence&nbsp; .-> confluence_agent;
	triage -. &nbsp;jira&nbsp; .-> jira_agent;
	triage -. &nbsp;status&nbsp; .-> status_agent;
	confluence_agent --> __end__;
	jira_agent --> __end__;
	status_agent --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
