---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	triage(triage)
	pizza_agent(pizza_agent)
	continuation_agent(continuation_agent)
	__end__([<p>__end__</p>]):::last
	__start__ --> triage;
	continuation_agent -.-> __end__;
	continuation_agent -.-> triage;
	pizza_agent -.-> continuation_agent;
	triage -.-> __end__;
	triage -.-> pizza_agent;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
